language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t chirag4904/doker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true chirag4904/doker-react npm run test